[[menu]]
  [[main]]
    name = "Home1"
    identifier = "home"
    url = "/"
    weight = 10
  [[main]] 
    name = "About Us"
    identifier = "briefabout"
    parent = "home"
    url = "tags/academic/"
    weight = 11
  [[main]] 
    name = "Current Projects"
    identifier = "currentprojects"
    parent = "home"
    url = "tags/academic/"
    weight = 12
  [[main]] 
    name = "Success Highlights"
    identifier = "success"
    parent = "home"
    url = "tags/academic/"
    weight = 13
  [[main]] 
    name = "Partners"
    identifier = "partners"
    parent = "home"
    url = "tags/academic/"
    weight = 14
  [[main]]
      name = "About Us"
      identifier = "about_us"
      url = "#about-us"
      weight = 20
  [[main]] 
    name = "Mission"
    identifier = "mission"
    parent = "about_us"
    url = "tags/academic/"
    weight = 21
  [[main]] 
    name = "Vision"
    identifier = "vision"
    parent = "about_us"
    url = "tags/academic/"
    weight = 22
  [[main]] 
    name = "History"
    identifier = "history"
    parent = "about_us"
    url = "tags/academic/"
    weight = 23
  [[main]] 
    name = "Foundation Values"
    identifier = "foundation"
    parent = "vision"
    url = "tags/academic/"
    weight = 24
  [[main]] 
    name = "Governance and Management"
    identifier = "governance"
    parent = "about_us"
    url = "tags/academic/"
    weight = 25
  [[main]] 
    name = "Footer"
    identifier = "footer1"
    parent = "governance"
    url = "tags/academic/"
    weight = 26
  [[main]]
      name = "Projects"
      identifier = "projects"
      url = "#projects"
      weight = 30
  [[main]] 
    name = "All Projects"
    identifier = "allprojects"
    parent = "projects"
    url = "tags/academic/"
    weight = 31
  [[main]] 
    name = "Current Projects"
    identifier = "currentprojects"
    parent = "projects"
    url = "tags/academic/"
    weight = 32
  [[main]] 
    name = "Our Success"
    identifier = "success"
    parent = "projects"
    url = "tags/academic/"
    weight = 34
  [[main]]
      name = "Media Center"
      identifier = "media_center"
      url = "post"
      weight = 40
  [[main]] 
    name = "Newsletters"
    identifier = "newsletters"
    parent = "media_center"
    url = "tags/academic/"
    weight = 41
  [[main]] 
    name = "Events/Activities"
    identifier = "eventsactivities"
    parent = "newsletters"
    url = "tags/academic/"
    weight = 41
  [[main]] 
    name = "Gallery"
    identifier = "gallery"
    parent = "media_center"
    url = "tags/academic/"
    weight = 42
  [[main]] 
    name = "Recent Activities"
    identifier = "recent"
    parent = "media_center"
    url = "tags/academic/"
    weight = 43
  [[main]] 
    name = "Reports"
    identifier = "reports"
    parent = "media_center"
    url = "tags/academic/"
    weight = 44
  [[main]] 
    name = "Footer"
    identifier = "footer"
    parent = "reports"
    url = "tags/academic/"
    weight = 45

  [[main]]
      name = "Support/Join Us"
      identifier = "support"
      url = "donate"
      weight = 50
  [[main]] 
      name = "Current Project Highlights"
      identifier = "currenthighlights"
      parent = "support"
      url = "tags/academic/"
      weight = 51
  [[main]] 
    name = "Payment Details"
    identifier = "paymentdetails"
    parent = "support"
    url = "tags/academic/"
    weight = 52

  [[main]]
      name = "Contact Us"
      identifier = "contact"
      url = "contact"
      weight = 60
  [[main]] 
    name = "Contact Form"
    identifier = "contactform"
    parent = "contact"
    url = "tags/academic/"
    weight = 61
  
  [[main]] 
    name = "Map"
    identifier = "map"
    parent = "contact"
    url = "tags/academic/"
    weight = 62
  [[main]] 
    name = "FAQ"
    identifier = "faq"
    parent = "contact"
    url = "tags/academic/"
    weight = 63

  [[main_right]]
    name = "Courses"
    identifier = "courses"
    url = "courses/"
    weight = 70

  [[main_right]]
    name = "Tutorial"
    identifier = "tutorial"
    url = "Tutorial"
    weight = 80
